export enum EvChargerState {
  VEHICLE_NOT_CONNECTED = 'VEHICLE_NOT_CONNECTED',
  VEHICLE_CONNECTED = 'VEHICLE_CONNECTED',
  CHARGING = 'CHARGING',
  CHARGING_COMPLETED = 'CHARGING_COMPLETED',
  ERROR = 'ERROR'
}
