version: '3'
services:
  # kann entfallen, wenn ein anderer MQTT-Broker verwendet wird
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    command:
      - /usr/sbin/mosquitto
      - -c
      - /mosquitto-no-auth.conf
    networks:
      macvlan0:
        # diese IP-Adresse oder der Container-Name muss in den Einstellung des Smart Appliance Enabler als MQTT Host eingetragen werden
        ipv4_address: 192.168.0.201
  pigpiod:
    # muss entfallen, falls der Smart Appliance Enabler nicht auf einem Raspberry Pi läuft
    image: zinen2/alpine-pigpiod
    container_name: pigpiod
    networks:
      macvlan0:
        ipv4_address: 192.168.0.202
    devices:
      - /dev/gpiochip0
    privileged: true
  sae:
    # anpassen, falls der Smart Appliance Enabler nicht auf einem Raspberry Pi läuft
    # Beispiel: image: avanux/smartapplianceenabler-arm32 (für Raspberry Pi)
    # Beispiel: image: avanux/smartapplianceenabler-amd64 (für PC / NAS)
    image: avanux/smartapplianceenabler-arm32
    container_name: sae
    restart: unless-stopped
    depends_on:
      # entfernen, falls ein anderer MQTT-Broker verwendet wird
     - mosquitto
      # entfernen, falls pigpiod nicht verwendet wird oder der Smart Appliance Enabler nicht auf einem Raspberry Pi läuft
     - pigpiod
    networks:
      macvlan0:
        # diese IP-Adresse wird dem Container zugewiesen, in dem der Smart Appliance Enabler läuft
        # Die Adresse muss in dem Adressbereich liegen, der weiter unten durch "iprange" definiert ist
        # Beispiel: ipv4_address: 192.168.0.200
        ipv4_address: 192.168.0.200
    volumes:
      - sae:/opt/sae/data
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      # in der nachfolgenden Zeile können Konfigurationsparameter an den Smart Appliance Enabler übergeben werden
      # Für mögliche Parameter siehe mit JAVA_OPTS beginnende Zeilen in https://github.com/camueller/SmartApplianceEnabler/blob/master/run/etc/default/smartapplianceenabler
      # Beispiel: JAVA_OPTS: '-Dserver.port=9000'
      # Bei Verwendung von pigpiod muss -DPIGPIOD_HOST auf die IP-Adresse oder den Container-Namen gesetzt sein, welche dem pigpiod-Container zugewiesen wurde
      JAVA_OPTS: '-DPIGPIOD_HOST=pigpiod'
    privileged: true
volumes:
  sae:
    name: sae
networks:
  macvlan0:
    name: macvlan0
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        # muss identisch mit dem Netz sein, dass zum Interface mit der Default-Route gehört
        # Beispiel: subnet 192.168.0.0/24 für 255 IP-Adressen von 192.168.0.1 bis 192.168.0.254
        - subnet: 192.168.0.0/24
          # Teilnetz des Netzes, das in "subnet" definiert ist, dessen IP-Adressen für Docker container verwendet werden können
          # Dieser Adressbereich muss vom DHCP-Server ignoriert werden, d.h. er darf diese Adresse niemandem zusteilen!!
          # Beispiel: ip_range: 192.168.0.192/27 für den Bereich von 192.168.0.193 bis 192.168.0.222 (IP Calculator: http://jodies.de/ipcalc)
          ip_range: 192.168.0.192/27
          # Ziel der Default-Route (meist die interne IP-Adresses des Internet-Routers).
          # Beispiel: gateway: 192.168.0.1
          gateway: 192.168.0.1
