pipeline {
    agent { label 'raspi2' }

    environment {
        VERSION = readMavenPom().getVersion()
    }

    stages {
        stage('Dockerize') {
            steps {
                sh "echo Version=$VERSION"
                dir('docker') {
                    sh 'cp ../../../SmartApplianceEnabler-"$VERSION".war sae-arm32/'
                    sh "sed -i 's#@project.version@#'\"$VERSION\"'#' ./sae-arm32/Dockerfile"
                    sh "docker build --tag=avanux/smartapplianceenabler-arm32:$VERSION ./sae-arm32"
                    /*
                    sh "docker tag avanux/smartapplianceenabler-arm32:$VERSION avanux/smartapplianceenabler-arm32:latest"
                    sh "docker image push avanux/smartapplianceenabler-arm32:$VERSION"
                    sh "docker image push avanux/smartapplianceenabler-arm32"
                    */
                }
            }
        }
    }
}
